In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
# Read in the data from the CSV file
url="Data/payment_fraud.csv"
df = pd.read_csv(url)

In [4]:
df.sample(30)

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
29657,2000,1,4.921318,paypal,0.001389,0
30238,1518,1,4.836982,creditcard,0.002083,0
12004,2,2,4.962055,creditcard,0.000000,0
31852,597,1,4.057414,creditcard,173.135417,0
30618,760,1,5.040929,creditcard,0.000000,0
35761,1685,1,5.017904,creditcard,844.989583,0
9882,1088,1,4.921349,creditcard,0.000000,0
36323,2000,1,4.505662,paypal,16.272222,0
9549,626,1,4.921318,creditcard,0.000000,0
21397,317,1,4.505662,creditcard,0.000000,0
34087,89,5,4.524580,creditcard,31.455556,0
9823,414,1,3.954522,creditcard,0.001389,0
2314,1619,1,5.034622,creditcard,0.049306,0
27696,957,1,4.745402,creditcard,0.052778,0
29013,2000,1,3.575983,creditcard,0.000000,0
10270,1805,1,4.962055,creditcard,0.002778,0
1520,959,1,4.962055,creditcard,404.081944,0
28089,1633,1,4.921318,creditcard,384.262500,0
35736,4,1,4.057414,paypal,0.000000,0
3493,6,1,5.034622,creditcard,0.000000,0
12645,189,1,4.505662,creditcard,0.000000,0
8045,162,3,4.895263,creditcard,0.000000,0
5960,1214,1,4.886641,creditcard,0.000000,0
25859,2000,1,4.965339,creditcard,572.766667,0
24817,176,1,4.524580,creditcard,6.216667,0
4730,2000,1,5.034622,creditcard,36.793056,0
1177,55,1,4.745402,creditcard,4.069444,0
27628,169,1,5.017904,creditcard,0.000000,0
3373,29,1,4.524580,paypal,28.952083,0
27508,3,1,4.836982,creditcard,0.000000,0

In [5]:
# Convert categorical feature into dummy variables with one-hot encoding
df = pd.get_dummies(df, columns=['paymentMethod'])
df.sample(3)

,accountAgeDays,numItems,localTime,paymentMethodAgeDays,label,paymentMethod_creditcard,paymentMethod_paypal,paymentMethod_storecredit
11563,220,1,4.962055,0.011111,0,True,False,False
12672,117,1,4.748314,0.002083,0,False,False,True
18127,2000,1,4.962055,0.000000,0,False,True,False

In [6]:
# Split dataset up into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('label', axis=1), df['label'],
    test_size=0.33, random_state=17)

In [7]:
# Initialize and train classifier model
clf = LogisticRegression().fit(X_train, y_train)

# Make predictions on test set
y_pred = clf.predict(X_test)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [8]:
# Compare test set predictions with ground truth labels
print(accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))

1.0
[[12753     0]
 [    0   190]]