In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
# Read in the data from the CSV file
url="https://raw.githubusercontent.com/oreilly-mlsec/book-resources/refs/heads/master/chapter2/datasets/payment_fraud.csv"
df = pd.read_csv(url)

In [ ]:
df.sample(30)

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
6840,1480,1,4.886641,paypal,0.000000,0
2202,1197,1,4.505662,creditcard,1.300694,0
1069,187,1,4.921318,creditcard,0.000000,0
16930,666,1,4.921318,creditcard,65.881250,0
7335,995,1,4.524580,creditcard,0.050694,0
26179,2000,1,4.921349,creditcard,0.000694,0
29631,853,1,5.034622,creditcard,0.000000,0
25358,34,1,4.962055,creditcard,0.000694,0
3703,1623,1,2.596228,paypal,20.410417,0
3279,2000,1,4.895263,paypal,0.000000,0
23915,17,1,4.921318,creditcard,0.000694,0
30225,1495,1,4.505662,creditcard,0.000000,0
30696,2000,1,5.040929,creditcard,222.534722,0
38210,2000,1,4.895263,paypal,617.404167,0
11225,107,1,4.886641,creditcard,0.000000,0
19823,118,1,4.876771,creditcard,0.000000,0
25918,1260,1,3.066058,paypal,0.000000,0
24657,1279,1,3.575983,paypal,0.056944,0
12528,37,1,4.745402,paypal,35.927778,0
36939,1637,1,5.034622,creditcard,295.836806,0
4638,115,1,5.040929,creditcard,0.000000,0
18843,1086,1,4.742303,paypal,297.518750,0
33781,198,1,4.876771,creditcard,171.756944,0
25069,51,1,4.921349,storecredit,0.000000,0
32891,16,1,4.965339,paypal,5.215278,0
21778,164,1,4.895263,creditcard,92.065972,0
5771,578,1,4.748314,creditcard,485.709028,0
13005,126,1,4.836982,creditcard,0.000000,0
14974,971,1,4.962055,creditcard,0.000000,0
8251,2000,1,4.748314,storecredit,0.000000,0

In [ ]:
# Convert categorical feature into dummy variables with one-hot encoding
df = pd.get_dummies(df, columns=['paymentMethod'])
df.sample(3)

,accountAgeDays,numItems,localTime,paymentMethodAgeDays,label,paymentMethod_creditcard,paymentMethod_paypal,paymentMethod_storecredit
592,2000,1,4.836982,0.000000,0,False,False,True
24980,2000,1,3.575983,0.020139,0,True,False,False
14596,668,1,4.748314,0.000000,0,True,False,False

In [ ]:
# Split dataset up into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('label', axis=1), df['label'],
    test_size=0.33, random_state=17)

In [ ]:
# Initialize and train classifier model
clf = LogisticRegression().fit(X_train, y_train)

# Make predictions on test set
y_pred = clf.predict(X_test)

In [ ]:
# Compare test set predictions with ground truth labels
print(accuracy_score(y_pred, y_test))
print(confusion_matrix(y_test, y_pred))

1.0
[[12753     0]
 [    0   190]]